### ISSUE TITLE
Page one shows what should be on page 2 and so on.

### ISSUE THREAD

**Issue by theoaks** [martijnboland/MvcPaging#47]
I observed that the items on the current page are actually items that should be on the next page.

**Comment by martijnboland** [comment]
Can you give an example? Screenshot? Live example? Environment? It's hard to guess what's going wrong.

**Comment by caojinqin** [comment]
@martijnboland:
 Hello, I've been using this page to your plug-in, but there are some still feel inadequate, for example, I want to do more than one condition Ajax paging query, then how to achieve it?
If you can join the plugin jquery template engine, I think even more perfect. Expect the next version to have these features, I'm not good at English, I'm sorry, I hope you can understand.

**Comment by martijnboland** [comment]
I don't think I'm going to add any new Ajax features myself, but feel free to send a pull request.

**Comment by martijnboland** [comment]
Closed because no response after 2 years
