### ISSUE TITLE
MVC 6 and DotNet Core?

### ISSUE THREAD

**Issue by joeaudette** [martijnboland/MvcPaging#49]
Hi Martijn,

Wondering if you have plans to implement this for MVC 6 and the new .NET Core framework? And if so any idea when it might become available?

I'm working on porting an MVC 5 app that uses your pager to MVC 6, so for the moment having to comment out the pagers and wait for a compatible version.

Thanks,

Joe

**Comment by martijnboland** [comment]
Sure, I'm very curious if it would be much work. Do you have any idea what doesn't work specifically right now? I'll give it a go next week or so.

**Comment by joeaudette** [comment]
Hi Martin,

I have to confess that I have not tried to use it, I think at very minimum it would need a nuget package that targets dnxcore50, the new small cross platform framework.

When you create an asp.net 5 project in VS 2015 RC the new project types target dnx451 which is equivalent to desktop framework and dnxcore50 which is the new small cross platform framework. As soon as you try to use something not supported in dnxcore50 you get errors.

I think people can still use MVC 5 and MVCPaging with dnx451 but they cannot target dnxcore50 with MVC 5 so I suspect the same for MVC Paging.

MVC 6 can run on either dnx451 or dnxcore50 but I think the cool kids are going to want to use dnxcore50.

To target dnxcore50, some big pieces are gone or changed. If MVCPaging uses anything from System.Web or System.Configuration, those do not exist in dnxcore50 but there are new more flexible config classes in Microsoft.Framework.ConfigurationModel namespace.

MVC 6 is in the new Microsoft.AspNet.MVC namespace and is integrated fully so web api controllers are the same as mvc controllers. So far in my own project I have found I needed to make minor changes in all of my HtmlHelper extensions.

Now there is a new thing called tag helpers that are much cleaner to use than HtmlHelpers for most things. For example this HtmlHelper type Razor syntax:

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
            </div>
        </div>

still works but can be made cleaner using tag helpers like this:

     <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="DisplayName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DisplayName" class="form-control" />
                <span asp-validation-for="DisplayName" class="text-danger"></span> 
            </div>
        </div>

I think this is the biggest and best transition in the history of asp.net, I am really liking the new framework.  We will even be able to use it on mac and linux, there is even a new code editor Visual Studio Code that can work on mac or linux as well and you can run the app from the command line etc. Exciting times I think.

Best Regards,

Joe

**Comment by martijnboland** [comment]
Very informative, thanks a lot Joe.

**Comment by martijnboland** [comment]
I've done a little fiddling the last couple of nights with MVC 6 and dnxcore50 (the just-released beta-5). It surely looks promising, but I also noticed that it's far from ready. They're expecting at least 3 beta's with possible breaking changes and a first RC with go-live is scheduled for november (according to the latest aspnet standup). For me personally, at this moment, it's too early to invest in a building a compatible version (also due to time constraints). However, I'd be glad to accept any pull requests or help facilitating dnxcore development.

**Comment by joeaudette** [comment]
I don't blame you. Myself the app I'm working on I'm hoping to release at roughly the same time as when asp.net 5/mvc 6/dnxcore50 is officially released so I'm trying to work with the latest bits. Most of the features are there, only a few things like Localization and AjaxHelpers is not ready and probably won't be till beta6 or beta7. Originally they were going to leave out the AjaxHelpers but now they say it will be implemented based on customer feedback. I'm finding that I can live without the AjaxHelpers with a few changes to my code though, whereas I'll just have to leave things un-localized until the localization framework bits are ready.

By coincidence I was just googling to find an example of custom taghelper for something else I need to implement and found this article which actually implements a simple pager.
http://www.mikesdotnetting.com/Article/275/custom-taghelpers-in-asp-net-mvc-6
I can probably use that to meet my paging needs at least for now.

There is also a new thing called viewcomponents, and navigation is one of the kinds of problems it is supposed to be useful for so it might be a good tool for a pager as well. I've also been using MVCSiteMapProvider which will probably not have a dnxcore50 version for a long time yet so I may try to hack together my own menus and breadcrumbs so I can move forward with my app.

I'm still working with beta4 at the moment and trying to get things basically working with my app which was started using MVC 5 and in the process of porting to MVC 6. I can already see there are some breaking changes in beta5 that I will have to work through when I update but none of it looks too difficult to resolve.

**Comment by martijnboland** [comment]
Joe created a new version for vnext: https://github.com/joeaudette/cloudscribe.Web.Pagination. This will also be the logical successor of MvcPaging for ASP.NET 5 / MVC6.
