### ISSUE TITLE
Not compatible with MVC 3

### ISSUE THREAD

**Issue by djsmlz** [martijnboland/MvcPaging#50]
Hi,

I am stuck with this error, is the library compatible with MVC3 or how do I go around this without upgrading to MVC4?

Error	1	Assembly 'MvcPaging, Version=2.1.2.28, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	
c:\*****\packages\MvcPaging.2.1.2\lib\net40\MvcPaging.dll	********

**Comment by martijnboland** [comment]
Not possible I'm afraid. I guess you could try an older version like 2.0.3 or 2.0.4.

**Comment by djsmlz** [comment]
Ok i will.
