### ISSUE TITLE
Update 2.1.2 -> 2.1.4 broke pager

### ISSUE THREAD

**Issue by idfarm** [martijnboland/MvcPaging#52]
Version 2.1.4 broke the pager. See images for a comparison:

Example pager with 8 pages (max: 3):
2.1.2
![image](https://cloud.githubusercontent.com/assets/16936411/12642640/67e36338-c5b7-11e5-953a-a431d8374e16.png)

2.1.4
![image](https://cloud.githubusercontent.com/assets/16936411/12642600/1dc34b42-c5b7-11e5-9968-d01aaf04a14a.png)

**Comment by martijnboland** [comment]
Fixed with #54
