### ISSUE TITLE
Weird behaviour when the list have just part of data

### ISSUE THREAD

**Issue by igor-krein** [martijnboland/MvcPaging#57]
Hi.

There is a little bug, it seems, though it appears in special (not very likely to happen) circumstances.

I am using the feature of creating PagedList from List with just part of all data (myList.ToPagedList(pageIndex, pageSize, totalItemCount)). Everything is OK when the count of list elements is equal or less than PageSize (which is quite natural). But suppose the list contains more elements than needed (say, 15 instead of 10). I think we should get PagedList of just first 10 items and drop the excess. But PagedList constructor works differently (when page number > 1).

The problem lies in this piece of code:

			var realTotalPages = (int)Math.Ceiling(realTotalCount / (double)PageSize);

			if (realTotalCount < TotalItemCount && realTotalPages <= PageIndex)
				AddRange(source.Skip((realTotalPages - 1) * PageSize).Take(PageSize));
			else
				AddRange(source.Skip(PageIndex * PageSize).Take(PageSize));

Maybe there is some reason for such a complex if statement, but I don't get it. For what puprose there is a realTotalPages variable? Maybe I am missing something.

Think, I could fix this part, but I'd like to be sure I get everything right.

**Comment by martijnboland** [comment]
To be honest, I don't exactly know why it's done this way. @bartlenaerts contributed this part, so maybe he still knows some of it? :)

But if you can fix this part, feel free to send a pull request and add some tests to verify the behavior that you'd expect. From those tests, I can easily tell if it will work out right.

Thanks!

**Comment by igor-krein** [comment]
Created a pull request. Still don't know what @bartlenaerts meant, but it seems that everything is OK (tests passed).

**Comment by martijnboland** [comment]
Released version 2.1.7 with fix. Thanks again, Igor!

**Comment by igor-krein** [comment]
You're welcome, Martijn!

Actually, I could look at other issues if there is a need. I'd like to practise C# a little and it'd make sense to practise and to do something useful at the same time.

**Comment by bartlenaerts** [comment]
Sorry, just back from holiday! Everything alright? Or still questions for me?

**Comment by martijnboland** [comment]
No problem, I think Igor managed just fine, but if you want, you could check the PR to see if we didn't miss anything (https://github.com/martijnboland/MvcPaging/pull/59).
