### ISSUE TITLE
mvcpaging conflicts with footable.js

### ISSUE THREAD

**Issue by vikasNew** [martijnboland/MvcPaging#58]
i have implemented mvcpaging, but this is conflicting with footable.js which was already exists.

i have used pagination css class of bootstrap, which is also used by footable. whenever i apply pagination class on div mvcpagination stops working.

i dont want to remove pagination css class.

**Comment by martijnboland** [comment]
We have to option to provide a custom DisplayTemplate, see http://demo.taiga.nl/mvcpaging/Paging/Bootstrap3 for an example. This allows you to completely customize the html that is generated by the pager. With this, you'll probably can work around this problem.
