### ISSUE TITLE
Are pretty URLs possible?

### ISSUE THREAD

**Issue by Ciwan1859** [martijnboland/MvcPaging#62]
Hi

I have integrated your code and paging works, but the URLs are not pretty URLs. What I would like them to be is:

> http://www.mysite.com/suppliers/page/1
> http://www.mysite.com/suppliers/page/2

And so on. Is this possible? Right now I'm getting:

> http://www.mysite.com/suppliers/page?page=2

Any help would be greatly appreciated.

**Comment by martijnboland** [comment]
Yes, this is possible with custom routes. See http://demo.taiga.nl/mvcpaging/SimplePaging. The route configuration for this page is: 
```c#
routes.MapRoute("SimplePaging", "SimplePaging/{page}",
                new { controller = "Paging", action = "Index", page = UrlParameter.Optional }); 
```
For the scenario above, you could probably use something like:
```c#
routes.MapRoute("DefaultPaged",  "{controller}/{action}/page/{page}", 
                new { controller = "Home", action = "Index", page = 1 },  // Parameter defaults
```
