### ISSUE TITLE
There is a bug for PagedList 

### ISSUE THREAD

**Issue by JeffreyChan** [martijnboland/MvcPaging#64]
I am sure it's bug for get item start and end.

here is your code:
`ItemStart = PageIndex * PageSize + 1;
 ItemEnd = Math.Min(PageIndex * PageSize + PageSize, TotalItemCount);`

If I just have 10 items, pageindex:1, pagesize:10,
Item-Start should be 1 not 11.

**Comment by martijnboland** [comment]
With 10 items and PageSize 10, PageIndex should be 0.
