### ISSUE TITLE
All page links pass parameters in url... 

### ISSUE THREAD

**Issue by hhq365** [martijnboland/MvcPaging#74]
Even the request method could choice POST...but parameters always in url... that's an issue...Url length is limited

**Comment by martijnboland** [comment]
To be honest, I've never considered paging with POST. Why would you want to do that? A querystring can be up to around 2000 chars nowadays.

**Comment by hhq365** [comment]
It's a scene of historical search function optimization.The function and parameters design are unreasonable now.So the querystring length had over the limit,then I found this issue.This make the param:AjaxOptions-HttpMethod out of action,it doesn't look very reasonable.I had to temporary use customize template to force it use ajax post.It's working well now.

**Comment by martijnboland** [comment]
Good to see you found a workaround. Just open a new issue when you run into other problems. Closing this for now.
