### ISSUE TITLE
Add options to hide first/last 2 pages + spacer.

### ISSUE THREAD

**Issue by leebarbara** [martijnboland/MvcPaging#76]
Hello there,
Could you please add an option to hide (or an option to show and hide by default) the first 2 pages and last 2 pages that are displayed? I believe https://github.com/martijnboland/MvcPaging/blob/master/src/MvcPaging/Pager.cs#L87 and https://github.com/martijnboland/MvcPaging/blob/master/src/MvcPaging/Pager.cs#L112 are doing it.

Thanks,
Barbara

**Comment by martijnboland** [comment]
Hi Barbara, since you've already dug into the code, is it perhaps possible to add this option yourself and create a pull-request over here? I'd be happy to integrate it and make a new release.

**Comment by leebarbara** [comment]
Hello! I've just created a pull request :) 
https://github.com/martijnboland/MvcPaging/pull/77
It would be really great if you can create a new release this week!
